# Form implementation generated from reading ui file 'Info.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Back(object):
    def setupUi(self, Back):
        Back.setObjectName("Back")
        Back.resize(800, 600)
        Back.setStyleSheet("background-color: rgb(231, 255, 239);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.centralwidget = QtWidgets.QWidget(parent=Back)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 181))
        self.frame.setStyleSheet(" background-color: rgb(194, 255, 172);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Info = QtWidgets.QPushButton(parent=self.frame)
        self.Info.setGeometry(QtCore.QRect(300, 60, 171, 61))
        self.Info.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Info.setObjectName("Info")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(610, 520, 171, 61))
        self.back.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.back.setObjectName("back")
        self.info_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.info_text.setGeometry(QtCore.QRect(60, 200, 671, 261))
        self.info_text.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;\n"
"")
        self.info_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.info_text.setWordWrap(True)
        self.info_text.setObjectName("info_text")
        Back.setCentralWidget(self.centralwidget)

        self.retranslateUi(Back)
        QtCore.QMetaObject.connectSlotsByName(Back)

    def retranslateUi(self, Back):
        _translate = QtCore.QCoreApplication.translate
        Back.setWindowTitle(_translate("Back", "MainWindow"))
        self.Info.setText(_translate("Back", "Information"))
        self.back.setText(_translate("Back", "Back"))
        self.info_text.setText(_translate("Back", "Our typing speed application project is designed for entertainment purposes, without a strong scientific focus. While similar resources already exist on the Internet, they are often imperfect, with users complaining about limited functionality, excessive advertising, a complex interface, and inflexible settings."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Back = QtWidgets.QMainWindow()
    ui = Ui_Back()
    ui.setupUi(Back)
    Back.show()
    sys.exit(app.exec())
