# Form implementation generated from reading ui file 'LogInNew.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogIn(object):
    def setupUi(self, LogInWindow):
        LogInWindow.setObjectName("LogInWindow")
        LogInWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        LogInWindow.setFont(font)
        LogInWindow.setStyleSheet("background-color: rgb(231, 255, 239);")
        self.centralwidget = QtWidgets.QWidget(parent=LogInWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogIn = QtWidgets.QLabel(parent=self.centralwidget)
        self.LogIn.setGeometry(QtCore.QRect(0, -10, 800, 181))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.LogIn.setFont(font)
        self.LogIn.setStyleSheet("background-color: rgb(194, 255, 172);")
        self.LogIn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LogIn.setObjectName("LogIn")
        self.Username = QtWidgets.QLabel(parent=self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(300, 180, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.Username.setFont(font)
        self.Username.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLabel(parent=self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(300, 450, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.Password.setFont(font)
        self.Password.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Password.setObjectName("Password")
        self.logIn_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logIn_button.setGeometry(QtCore.QRect(622, 517, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.logIn_button.setFont(font)
        self.logIn_button.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;\n"
"")
        self.logIn_button.setObjectName("logIn_button")
        self.UsernameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(310, 270, 181, 41))
        self.UsernameInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PasswordInput.setGeometry(QtCore.QRect(310, 530, 181, 41))
        self.PasswordInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PasswordInput.setObjectName("PasswordInput")
        self.logIn_button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logIn_button_2.setGeometry(QtCore.QRect(50, 517, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.logIn_button_2.setFont(font)
        self.logIn_button_2.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;\n"
"")
        self.logIn_button_2.setObjectName("logIn_button_2")
        self.EmailLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.EmailLbl.setGeometry(QtCore.QRect(300, 320, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.EmailLbl.setFont(font)
        self.EmailLbl.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.EmailLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EmailLbl.setObjectName("EmailLbl")
        self.EmailTxt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EmailTxt.setGeometry(QtCore.QRect(310, 400, 181, 41))
        self.EmailTxt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EmailTxt.setObjectName("EmailTxt")
        LogInWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogInWindow)
        QtCore.QMetaObject.connectSlotsByName(LogInWindow)

    def retranslateUi(self, LogInWindow):
        _translate = QtCore.QCoreApplication.translate
        LogInWindow.setWindowTitle(_translate("LogInWindow", "MainWindow"))
        self.LogIn.setText(_translate("LogInWindow", "Log in"))
        self.Username.setText(_translate("LogInWindow", "Username"))
        self.Password.setText(_translate("LogInWindow", "Password"))
        self.logIn_button.setText(_translate("LogInWindow", "Log in"))
        self.logIn_button_2.setText(_translate("LogInWindow", "Back"))
        self.EmailLbl.setText(_translate("LogInWindow", "E-mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogInWindow = QtWidgets.QMainWindow()
    ui = Ui_LogIn()
    ui.setupUi(LogInWindow)
    LogInWindow.show()
    sys.exit(app.exec())
