# Form implementation generated from reading ui file 'MAIN_WINDOW.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        MainWindow1.setObjectName("MainWindow1")
        MainWindow1.setEnabled(True)
        MainWindow1.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow1.setFont(font)
        MainWindow1.setStyleSheet("background-color: rgb(231, 255, 239);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        MainWindow1.setAnimated(True)
        MainWindow1.setDockOptions(QtWidgets.QMainWindow1.AllowTabbedDocks|QtWidgets.QMainWindow1.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.Try_your_speed = QtWidgets.QLabel(parent=self.centralwidget)
        self.Try_your_speed.setGeometry(QtCore.QRect(270, 200, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.Try_your_speed.setFont(font)
        self.Try_your_speed.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Try_your_speed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Try_your_speed.setObjectName("Try_your_speed")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(220, 270, 381, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.our_text_for_typing = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.our_text_for_typing.setGeometry(QtCore.QRect(110, 310, 591, 221))
        self.our_text_for_typing.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.our_text_for_typing.setObjectName("our_text_for_typing")
        self.User_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.User_text.setGeometry(QtCore.QRect(110, 310, 591, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.User_text.sizePolicy().hasHeightForWidth())
        self.User_text.setSizePolicy(sizePolicy)
        self.User_text.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"border: none;")
        self.User_text.setObjectName("User_text")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 181))
        self.frame.setStyleSheet(" background-color: rgb(194, 255, 172);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.account = QtWidgets.QPushButton(parent=self.frame)
        self.account.setGeometry(QtCore.QRect(30, 10, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.account.setFont(font)
        self.account.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.account.setObjectName("account")
        self.Rating = QtWidgets.QPushButton(parent=self.frame)
        self.Rating.setGeometry(QtCore.QRect(320, 10, 171, 61))
        self.Rating.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Rating.setObjectName("Rating")
        self.Settings = QtWidgets.QPushButton(parent=self.frame)
        self.Settings.setGeometry(QtCore.QRect(610, 10, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Settings.setFont(font)
        self.Settings.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Settings.setObjectName("Settings")
        self.Info = QtWidgets.QPushButton(parent=self.frame)
        self.Info.setGeometry(QtCore.QRect(470, 90, 171, 61))
        self.Info.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Info.setObjectName("Info")
        self.achievements = QtWidgets.QPushButton(parent=self.frame)
        self.achievements.setGeometry(QtCore.QRect(180, 90, 171, 61))
        self.achievements.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.achievements.setObjectName("achievements")
        self.Start_again = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Start_again.setGeometry(QtCore.QRect(650, 550, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.Start_again.setFont(font)
        self.Start_again.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Start_again.setObjectName("Start_again")
        MainWindow1.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow1)

    def retranslateUi(self, MainWindow1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1.setWindowTitle(_translate("MainWindow1", "MainWindow1"))
        self.Try_your_speed.setText(_translate("MainWindow1", "Try your speed typing"))
        self.account.setText(_translate("MainWindow1", "Account"))
        self.Rating.setText(_translate("MainWindow1", "Rating"))
        self.Settings.setText(_translate("MainWindow1", "Settings"))
        self.Info.setText(_translate("MainWindow1", "Information"))
        self.achievements.setText(_translate("MainWindow1", "Achievements"))
        self.Start_again.setText(_translate("MainWindow1", "Start again"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow1 = QtWidgets.QMainWindow1()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec())
