# Form implementation generated from reading ui file 'Rating.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Rating(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(231, 255, 239);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 181))
        self.frame.setStyleSheet(" background-color: rgb(194, 255, 172);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Rating = QtWidgets.QPushButton(parent=self.frame)
        self.Rating.setGeometry(QtCore.QRect(290, 40, 221, 81))
        self.Rating.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.Rating.setObjectName("Rating")
        self.FastestTypers = QtWidgets.QPushButton(parent=self.centralwidget)
        self.FastestTypers.setGeometry(QtCore.QRect(70, 200, 301, 71))
        self.FastestTypers.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.FastestTypers.setObjectName("FastestTypers")
        self.OldestTypers = QtWidgets.QPushButton(parent=self.centralwidget)
        self.OldestTypers.setGeometry(QtCore.QRect(440, 200, 301, 71))
        self.OldestTypers.setStyleSheet("background-color: rgb(235, 255, 197);\n"
"border-radius: 25px;")
        self.OldestTypers.setObjectName("OldestTypers")
        self.scrollFast = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollFast.setGeometry(QtCore.QRect(100, 280, 241, 291))
        self.scrollFast.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollFast.setWidgetResizable(True)
        self.scrollFast.setObjectName("scrollFast")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 239, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollFast.setWidget(self.scrollAreaWidgetContents)
        self.scrollDays = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollDays.setGeometry(QtCore.QRect(470, 280, 241, 291))
        self.scrollDays.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollDays.setWidgetResizable(True)
        self.scrollDays.setObjectName("scrollDays")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 239, 289))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollDays.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Rating.setText(_translate("MainWindow", "Rating"))
        self.FastestTypers.setText(_translate("MainWindow", "\"The fastest typers\""))
        self.OldestTypers.setText(_translate("MainWindow", "People that are with us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
